# command line: test.py

base_lr: 0.0001
batch_size: 1
config: null
debug: false
device: 0
eval_interval: 5
feeder: feeder.feeder
ignore_weights: []
log_interval: 100
model: null
model_args: {}
nesterov: true
num_epoch: 80
num_worker: 4
optimizer: Adam
pavi_log: false
phase: train
print_log: true
save_interval: 10
save_log: true
save_result: false
show_acc:
- 1
start_epoch: 0
step: []
test_batch_size: 1
test_feeder_args: {}
train_feeder_args: {}
use_gpu: true
weight_decay: 0.1
weights: null
work_dir: ./work_dir/tmp
