# command line: main.py recognition -c data/03/train.yaml

base_lr: 0.0001
batch_size: 1
config: data/03/train.yaml
debug: false
device:
- 0
- 1
- 2
- 3
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.fai_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: openpose
        strategy: spatial
    in_channels: 3
    num_class: 2
nesterov: true
num_epoch: 500
num_worker: 4
optimizer: Adam
pavi_log: false
phase: train
print_log: true
save_interval: 10
save_log: true
save_result: false
show_acc:
- 1
start_epoch: 0
step:
- 100
- 200
- 300
- 400
- 500
test_batch_size: 1
test_feeder_args:
    data_path: ./data/03/kinetics-skeleton/val_data.npy
    label_path: ./data/03/kinetics-skeleton/val_label.pkl
train_feeder_args:
    data_path: ./data/03/kinetics-skeleton/train_data.npy
    label_path: ./data/03/kinetics-skeleton/train_label.pkl
    random_choose: true
    random_move: true
    window_size: 300
use_gpu: true
weight_decay: 0.1
weights: null
work_dir: ./work_dir/recognition/kinetics_skeleton/FAI_GCN
